namespace HLE.Emojis;

/// <summary>
/// A class that contains (almost) all existing emojis.
/// </summary>
public static partial class Emoji
{
    // members are generated by source generator
    // emojis will be string constants, e.g.:
    // public const string Grinning = "😀";
}
