namespace HLE.Emojis;

/// <summary>
/// A class that contains (almost) all existing emojis.
/// </summary>
public static partial class Emoji
{
    // Members are generated by a source generator.
    // Emojis will be string constants, e.g.:
    // public const string Grinning = "😀";
}
